### ISSUE TITLE
Set up docs for Sharezone

### ISSUE THREAD

**Issue by nilsreichardt** [SharezoneApp/sharezone-app#166]
## Description
Currently, we use ZenDesk for our public docs and FAQ: https://sharezone.net/faq. Our goal is to move away from ZenDesk and use another Git based documentation tool, like [Riverpod](https://riverpod.dev/docs/getting_started), [FVM](https://fvm.app/docs/getting_started/overview) have.

The advantage is that it's free (instead of ZenDesk) and the community can easily participate ❤️ 

## ToDo
* [ ] Research for an open source documentation software (should also support multiple languages)
* [ ] Set up first proof of concept to make a decision
* [ ] Set up the software in this repository (+ hosting)
* [x] Set up CI/CD

**Comment by nilsreichardt** [comment]
Basic docs are set up.
