### ISSUE TITLE
Public Repository Checklist

### ISSUE THREAD

**Issue by Jonas-Sander** [SharezoneApp/sharezone-app#87]
- [x] Toggle `main` to protected.
- [x] Activate CLA assistent
- [x] Add link to CLA assistent in https://github.com/SharezoneApp/public/wiki/Sharezone-CLA-Overview
